### ISSUE TITLE
The URL for downloading the Dortmund dataset seems expired. Where can I download it now?

### ISSUE THREAD

**Issue by YanMENG-CVRS** [marian42/pointcloud#1]
Hello，I'm trying to download the Dortmund dataset (the pointcloud dataset) through “https://www.opengeodata.nrw.de/produkte/geobasis/dom/dom1l/dom1l_05913000_Dortmund_EPSG25832_XYZ.zip”. But  it displays "The requested URL /produkte/geobasis/dom/dom1l/dom1l_05913000_Dortmund_EPSG25832_XYZ.zip was not found on this server. "  Where can I download it now? Can you help me? Thanks a lot!

**Comment by YanMENG-CVRS** [comment]
My email address is mengyan@whu.edu.cn. If needed, you can contact me by email. Thank you!

**Comment by marian42** [comment]
Oh that's too bad :( I don't know why they removed it. I guess you'll have to ask someone at the NRW data portal. If it helps, "DOM" stands for "Digitales Oberflächenmodell" and 1 is the resolution (1m).

I also have a copy of the dataset on my PC. If you know of a way to transfer 25GB, I can make it available to you.

**Comment by YanMENG-CVRS** [comment]
I will come up with a way as soon as possible. Thank you for replying.

**Comment by YanMENG-CVRS** [comment]
I found Google drive very fast if we use their PC client. Is it convinent for you to use Google drive? Each free account has a  capacity of 15 GB.  Anyone who has a Google account own a Google drive account. You can upload the dataset to your Google drive and share a link to me, and then I can download the dataset in my city.

**Comment by YanMENG-CVRS** [comment]
In fact, I only want the pointcloud dataset. （If it's with class label, i.e., it's classified, it would be much better. ）Is a capacity of 15 GB large enough to transfer only the pointcloud dataset one time? If it isn't, you can split it into two parts and transfer two times: you upload one half, share it to me; after I have downloaded the first half, you delete it from your Google drive and upload the other half, and share it to me again.

**Comment by YanMENG-CVRS** [comment]
If your Google drive does not have enough free space, you can use my Google drive: you log in my account, upload the dataset and then I can download the dataset in my city.

**Comment by marian42** [comment]
The dataset is 25.5 GB, it's already compressed and it only contains .xyz files with laser scan points. It has no labels. There are some smaller datasets of other cities (instead of Dortmund), if you want a smaller size. I can also send you just some of the .xyz files, which are ~300 MB each. If you have enough space on your google drive, you can create a folder and give me access to it (mail@marian42.de) and I'll upload it there.

**Comment by YanMENG-CVRS** [comment]
I'v expanded the capacity of my Google drive to 100 GB so that you can upload the 25.5 GB dataset one time. The account and password of my Google drive have been sent to your email. Thank you very much!
